-- OBJECT: core.observation_numerical_specimen, observation_phys_chem, property_numerical_specimen, result_numerical_specimen, result_phys_chem
-- ISSUE: use IDENTITY instead of SEQUENCE


ALTER TABLE IF EXISTS core.observation_phys_chem_element ALTER COLUMN observation_phys_chem_element_id DROP DEFAULT;
DROP SEQUENCE IF EXISTS core.observation_phys_chem_observation_phys_chem_id_seq;
ALTER TABLE IF EXISTS core.observation_phys_chem_element ALTER COLUMN observation_phys_chem_element_id ADD GENERATED BY DEFAULT AS IDENTITY ( START 1008 );

ALTER TABLE IF EXISTS core.observation_phys_chem_specimen ALTER COLUMN observation_phys_chem_specimen_id DROP DEFAULT;
DROP SEQUENCE IF EXISTS core.observation_numerical_specime_observation_numerical_specime_seq;
ALTER TABLE IF EXISTS core.observation_phys_chem_specimen ALTER COLUMN observation_phys_chem_specimen_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE IF EXISTS core.result_phys_chem_element ALTER COLUMN result_phys_chem_element_id DROP DEFAULT;
DROP SEQUENCE IF EXISTS core.result_phys_chem_result_phys_chem_id_seq;
ALTER TABLE IF EXISTS core.result_phys_chem_element ALTER COLUMN result_phys_chem_element_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE IF EXISTS core.result_phys_chem_specimen ALTER COLUMN result_phys_chem_specimen_id DROP DEFAULT;
DROP SEQUENCE IF EXISTS core.result_numerical_specimen_result_numerical_specimen_id_seq;
ALTER TABLE IF EXISTS core.result_phys_chem_specimen ALTER COLUMN result_phys_chem_specimen_id ADD GENERATED BY DEFAULT AS IDENTITY;
