-- OBJECT: core.observation_phys_chem_element, observation_phys_chem_specimen
-- ISSUE: redundancy between these two tables


ALTER TABLE IF EXISTS core.result_phys_chem_element DROP CONSTRAINT fk_observation_phys_chem;
ALTER TABLE IF EXISTS core.observation_phys_chem_element RENAME TO observation_phys_chem;
ALTER TABLE IF EXISTS core.observation_phys_chem RENAME COLUMN observation_phys_chem_element_id TO observation_phys_chem_id;
ALTER TABLE IF EXISTS core.result_phys_chem_element RENAME COLUMN observation_phys_chem_element_id TO observation_phys_chem_id;
ALTER TABLE IF EXISTS core.result_phys_chem_element ADD FOREIGN KEY (observation_phys_chem_id)
    REFERENCES core.observation_phys_chem (observation_phys_chem_id);

ALTER TABLE IF EXISTS core.result_phys_chem_specimen DROP CONSTRAINT fk_observation_numerical_specimen;
ALTER TABLE IF EXISTS core.result_phys_chem_specimen DROP CONSTRAINT result_numerical_specimen_unq;
ALTER TABLE IF EXISTS core.result_phys_chem_specimen RENAME COLUMN observation_phys_chem_specimen_id TO observation_phys_chem_id;
ALTER TABLE IF EXISTS core.result_phys_chem_specimen ADD UNIQUE (observation_phys_chem_id, specimen_id);
ALTER TABLE IF EXISTS core.result_phys_chem_specimen ADD FOREIGN KEY (observation_phys_chem_id) REFERENCES core.observation_phys_chem(observation_phys_chem_id);
DROP TABLE IF EXISTS core.observation_phys_chem_specimen;







-- CREATE TABLE core.result_phys_chem_element (
-- 	result_phys_chem_element_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
-- 	observation_phys_chem_id int4 NOT NULL,
-- 	element_id int4 NOT NULL,
-- 	individual_id int4 NULL,
-- 	value float4 NOT NULL,
-- 	CONSTRAINT result_phys_chem_pkey PRIMARY KEY (result_phys_chem_element_id),
-- 	CONSTRAINT result_phys_chem_unq UNIQUE (observation_phys_chem_id, element_id),
-- 	CONSTRAINT result_phys_chem_unq_foi_obs UNIQUE (element_id, observation_phys_chem_id),
-- 	CONSTRAINT fk_element FOREIGN KEY (element_id) REFERENCES core."element"(element_id),
-- 	CONSTRAINT fk_individual FOREIGN KEY (individual_id) REFERENCES metadata.individual(individual_id),
-- 	CONSTRAINT result_phys_chem_element_observation_phys_chem_id_fkey FOREIGN KEY (observation_phys_chem_id) REFERENCES core.observation_phys_chem(observation_phys_chem_id)
-- );


-- CREATE TABLE core.result_phys_chem_specimen (
-- 	observation_phys_chem_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
-- 	observation_phys_chem_specimen_id int4 NOT NULL,
-- 	specimen_id int4 NOT NULL,
-- 	individual_id int4 NULL,
-- 	value float4 NOT NULL,
-- 	CONSTRAINT result_numerical_specimen_pkey PRIMARY KEY (observation_phys_chem_id),
-- 	CONSTRAINT result_phys_chem_specimen_observation_phys_chem_id_specimen_key UNIQUE (observation_phys_chem_id, specimen_id),
-- 	CONSTRAINT fk_specimen FOREIGN KEY (specimen_id) REFERENCES core.specimen(specimen_id),
-- 	CONSTRAINT result_phys_chem_specimen_individual_id_fkey FOREIGN KEY (individual_id) REFERENCES metadata.individual(individual_id),
-- 	CONSTRAINT result_phys_chem_specimen_observation_phys_chem_id_fkey FOREIGN KEY (observation_phys_chem_id) REFERENCES core.observation_phys_chem(observation_phys_chem_id)
-- );
