-- OBJECT: result_spectral
-- ISSUE: add objects to store spectral data


CREATE TABLE core.result_spectral (
	result_spectral_id  int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	observation_phys_chem_id int4 NOT NULL,
	specimen_id int4 NOT NULL,
	individual_id int4 NULL,
	payload jsonb NULL,
	CONSTRAINT result_spectral_pkey PRIMARY KEY (result_spectral_id),
	CONSTRAINT result_spectral_observation_phys_chem_id_specimen_key UNIQUE (observation_phys_chem_id, specimen_id),
	CONSTRAINT fk_specimen FOREIGN KEY (specimen_id) REFERENCES core.specimen(specimen_id),
	CONSTRAINT result_spectral_individual_id_fkey FOREIGN KEY (individual_id) REFERENCES metadata.individual(individual_id),
	CONSTRAINT result_spectral_observation_phys_chem_id_fkey FOREIGN KEY (observation_phys_chem_id) REFERENCES core.observation_phys_chem(observation_phys_chem_id)
);
CREATE INDEX result_spectral_observation_phys_chem_id_idx ON core.result_spectral USING btree (observation_phys_chem_id);
CREATE INDEX result_spectral_payload_idx ON core.result_spectral USING gin (payload);
