-- OBJECT: result_spectrum
-- ISSUE: add objects to store spectrum data


CREATE TABLE core.result_spectrum (
	result_spectrum_id  int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	specimen_id int4 NOT NULL,
	individual_id int4 NULL,
	spectrum jsonb NULL,
	CONSTRAINT result_spectrum_pkey PRIMARY KEY (result_spectrum_id),
	CONSTRAINT fk_specimen FOREIGN KEY (specimen_id) REFERENCES core.specimen(specimen_id),
	CONSTRAINT result_spectrum_individual_id_fkey FOREIGN KEY (individual_id) REFERENCES metadata.individual(individual_id)
);
CREATE INDEX result_spectrum_specimen_id_idx ON core.result_spectrum USING btree (specimen_id);
CREATE INDEX result_spectrum_spectrum_idx ON core.result_spectrum USING gin (spectrum);
